// packages/we-love-ds-angular/src/app/app.component.ts
/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */

import { Component } from '@angular/core';
import { RouterOutlet } from '@angular/router';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet],
  templateUrl: './app.component.html',
  styleUrl: './app.component.css'
})
export class AppComponent {
  title = 'we-love-ds-angular';
}

// sites/weLoveDesign-site-test/src/App.tsx
/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */

import { Button, Input, Label } from "weloveds";

function App() {
  return (
    <div>
      <Label>Site Test We Love Design</Label>
      <Input />
      <Button >wld button</Button>
    </div>
  );
}

export default App;
